export const sample_fuels = [
  {
    id: "1",
    name: "Liquid Petroleum Gas (LPG)",
    time: "10-20",
    price: 955,
    favorite: false,
    origins: ["india"],
    stars: 4.5,
    imageUrl: "fuel-1.jpg",
    tags: ["LPG"],
  },
  {
    id: "2",
    name: "Compressed Natural Gas (CNG)",
    price: 91.64,
    time: "20-30",
    favorite: true,
    origins: ["persia", "middle east", "china"],
    stars: 5,
    imageUrl: "fuel-2.jpg",
    tags: ["CNG", "Cost Effective"],
  },
  {
    id: "3",
    name: "Diesel",
    price: 97.82,
    time: "10-15",
    favorite: false,
    origins: ["germany", "us"],
    stars: 3.5,
    imageUrl: "fuel-3.jpg",
    tags: ["Diesel", "Fuel"],
  },
  {
    id: "4",
    name: "Petrol",
    price: 109.66,
    time: "15-20",
    favorite: true,
    origins: ["belgium", "france"],
    stars: 3,
    imageUrl: "fuel-4.jpg",
    tags: ["Petrol", "Fuel"],
  },
  {
    id: "5",
    name: "Petrol Ultra",
    price: 112.37,
    time: "40-50",
    favorite: false,
    origins: ["india", "asia"],
    stars: 3.5,
    imageUrl: "fuel-5.jpg",
    tags: ["Petrol", "Ultra", "Fuel"],
  },
  {
    id: "6",
    name: "Petrol Power",
    price: 123.05,
    time: "40-50",
    favorite: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "fuel-6.jpg",
    tags: ["Petrol", "Power", "Fuel"],
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "Petrol", count: 3 },
  { name: "Power", count: 1 },
  { name: "Diesel", count: 1 },
  { name: "Ultra", count: 1 },
  { name: "Fuel", count: 4 },
  { name: "CNG", count: 1 },
  { name: "LPG", count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto",
    isAdmin: false,
  },
  {
    id: 2,
    name: "ram",
    email: "ram@gmail.com",
    password: "12345",
    address: "india",
    isAdmin: true,
  },
];
